server:
  port: 3003
logging:
  level:
    root: INFO
    com.sandyz.bobtimerserver: TRACE
spring:
  application:
    name: BobTimerServer
  datasource:
    name: bob_timer
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bob_timer?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password:

  data:
    redis:
      host: localhost
      port: 6379
      database: 2
      password:
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql